- name: Cluster Logging Operator Checkpoint Start
  hosts: all
  gather_facts: true
  tasks:
  - name: Install Elastic Search Operator
    include_role:
      name: ocp-deploy-operator
    vars:
      op_namespace: "openshift-operators-redhat"
      pck_name: "elasticsearch-operator"
      op_ns_lables:
        openshift.io/cluster-logging: true
        openshift.io/cluster-monitoring: true
      rbac:
        set_role: true
        role: "{{ elastic_role }}"
        rolebinding_subject: 
          kind: "ServiceAccount"
          name: "{{ elastic_role.name }}"
      

  - name: Install Logging Operator
    include_role:
      name: ocp-deploy-operator
    vars:
      op_namespace: "openshift-logging"
      pck_name: "cluster-logging"
      op_ns_lables:
        openshift.io/cluster-logging: true
        openshift.io/cluster-monitoring: true
      operatorgroup:
        spec:
          targetNamespaces: 
            - openshift-logging
      additional_resource_templates:
        - crd_clusterlogging.yml.j2