
- name: Operator - Create OperatorGroup
  delegate_to: localhost
  k8s:
    kind: OperatorGroup
    name: "{{ operator.name }}"
    namespace: "{{ operator.namespace }}"
    resource_definition: "{{ lookup('template', 'operatorgroup.yml.j2')}}"
    state: "{{ operator.state | default('present') }}"
    kubeconfig: "{{ kube_config_path }}"

